# Generated by Django 5.1 on 2024-08-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=500, verbose_name='الاسم : '),
        ),
    ]
