# Generated by Django 5.1 on 2024-08-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_address_detail_alter_profile_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default=1, max_length=80, verbose_name='نبذة'),
            preserve_default=False,
        ),
    ]
