# Generated by Django 5.1 on 2024-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='التخصص  '),
        ),
    ]
