# Generated by Django 5.1 on 2024-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_specialist_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعات العمل '),
        ),
    ]
